/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module tt_um_dratini0_i2c(uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n, ui_in);
  wire \$2 ;
  wire [7:0] \$4 ;
  input clk;
  wire clk;
  wire \clk$1 ;
  input ena;
  wire ena;
  wire rst;
  input rst_n;
  wire rst_n;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  assign \$2  = ~ rst_n;
  assign \$4  = ~ ui_in;
  assign uio_oe = ui_in;
  assign uio_out = 8'h00;
  assign uo_out = \$4 ;
  assign rst = \$2 ;
  assign \clk$1  = clk;
endmodule

